### ISSUE TITLE
New 1.6.0 version is available

### ISSUE THREAD

**Issue by alexeiroz** [flathub/com.sleepfiles.OSCAR#12]
There is a new 1.6.0 version available at https://www.sleepfiles.com/OSCAR.
Could you please release an update for Fluthub?

**Comment by doccaz** [comment]
Working on it.

**Comment by doccaz** [comment]
Trying to just update the source to the new repository + version for now in #13 .

**Comment by doccaz** [comment]
Done! New build runs fine.
